server:
  port: 8082
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            "[non_contextual_creation]": true
          "[use_streams_for_binary]": false
    open-in-view: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

keycloak:
  realm: ${KC_REALM}
  auth-server-url: ${KC_AUTH_SERVER_URL}
  ssl-required: ${KC_SSL_REQUIRED}
  resource: ${KC_RESOURCE}
  public-client: true
  confidential-port: 0
