spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
  
  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USER}
    password: ${env.DB_PASS}
    hikari:
      auto-commit: false
keycloak:
  realm: ${env.KC_REALM}
  auth-server-url: ${env.KC_AUTH_SERVER_URL}
  ssl-required: ${env.KC_SSL_REQUIRED}
  resource: ${env.KC_RESOURCE}
  credentials:
    secret: ${env.KC_CREDENTIALS_SECRET}
  use-resource-role-mappings: true
  bearer-only: true